#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@glqos[-1]
	add ucitrack glqos
	set ucitrack.@glqos[-1].init=glqos
	commit ucitrack
	delete firewall.glqos
	set firewall.glqos=include
	set firewall.glqos.type=script
	set firewall.glqos.path=/usr/sbin/glqos.sh
	set firewall.glqos.reload=1
	commit firewall
EOF
exit 0
