#!/bin/sh

. /lib/functions.sh
. /lib/functions/network.sh

#echo "INTERFACE=$INTERFACE DEVICE=$DEVICE" >/dev/console
if [ "$INTERFACE" = "wan" -o "$INTERFACE" = "wwan" -o "$INTERFACE" = "tethering" -o "$INTERFACE" = "modem" -o "$INTERFACE" = "modem1" -o "$INTERFACE" = "modem_4" ];then
	if [ "$ACTION" == "ifup" ];then
		network_get_device device $INTERFACE
		#echo "device=$device" >/dev/console
		curwaniface=`ip route get 8.8.8.8 | awk '{print $5}'`
		if [ "$device" != "curwaniface" ];then
			sleep 10 && /usr/sbin/glqos.sh
		fi
	elif [ "$ACTION" == "ifdown" ];then
		iptables -t mangle -D PREROUTING -j QOS_UP
		iptables -t mangle -F QOS_UP
		iptables -t mangle -X QOS_UP
		if [ "$INTERFACE" = "wan" ];then
			wanif=`uci get network.wan.ifname`
		elif [ "$INTERFACE" = "wwan" ];then
			wanif=`uci get network.wwan.ifname`
		elif [ "$INTERFACE" = "tethering" ];then
			wanif=`uci get network.tethering.ifname`
		elif [ "$INTERFACE" = "modem" -o "$INTERFACE" = "modem_4" ];then
			wanif=`uci get network.modem.ifname`
		elif [ "$INTERFACE" = "modem1" -o "$INTERFACE" = "modem_4" ];then
			wanif=`uci get network.modem1.ifname`
		fi
		tc qdisc del dev $wanif root
		tc qdisc del dev br-lan root
	fi
fi
