#!/bin/sh

INTERFACES="wan wwan modem tethering wg ovpn"

[ -f "/etc/vpn.user" ] && {
	for interface in ${INTERFACES}; do
		[ "$interface" = "$INTERFACE" ] && {
			env -i ACTION="$ACTION" INTERFACE="$INTERFACE" DEVICE="$DEVICE" \
				/bin/sh /etc/vpn.user
		}
	done
}

exit 0
