#!/bin/sh /etc/rc.common

START=50

start() {
	local enabled

	config_load glfw
	config_get_bool enabled globals 'enabled' 0
	[ "$enabled" = "0" ] && {
		exit 0
	}

	/usr/bin/glfw start
}

stop() {
	/usr/bin/glfw stop
}
