#!/bin/sh /etc/rc.common
#
# Copyright (C) 2017
#
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#

START=90

NAME=vpn-service

set_network() {
	uci set network.vpn="interface"
	uci set network.vpn.ifname="tun0"
	uci set network.vpn.proto="none"
	uci set network.vpn.auto="1"

	uci commit network
	/etc/init.d/network reload

	return 0
}

set_firewall() {
	local proto=$(uci get vpn_service.vpn.proto)
	local port=$(uci get vpn_service.vpn.port)
	uci set firewall.vpn_server_rule="rule"
	uci set firewall.vpn_server_rule.name="Allow-OpenVPN-Inbound"
	uci set firewall.vpn_server_rule.target="ACCEPT"
	uci set firewall.vpn_server_rule.src="wan"
	uci set firewall.vpn_server_rule.proto=$proto
	uci set firewall.vpn_server_rule.dest_port=$port

	uci set firewall.vpn_server_zone="zone"
	uci set firewall.vpn_server_zone.name="vpn-server"
	uci set firewall.vpn_server_zone.input="ACCEPT"
	uci set firewall.vpn_server_zone.forward="ACCEPT"
	uci set firewall.vpn_server_zone.output="ACCEPT"
	uci set firewall.vpn_server_zone.masq="1"
	uci set firewall.vpn_server_zone.device="tun-SERVER"

	uci set firewall.vpn_server_wan="forwarding"
	uci set firewall.vpn_server_wan.src="vpn-server"
	uci set firewall.vpn_server_wan.dest="wan"

	uci set firewall.vpn_server_lan="forwarding"
	uci set firewall.vpn_server_lan.src="vpn-server"
	uci set firewall.vpn_server_lan.dest="lan"

	uci commit firewall
	/etc/init.d/firewall reload

	return 0
}

flush_rules() {
	iptables-save -c | grep -v "vpn" | iptables-restore -c

	# clear vpn firewall
	uci delete firewall.vpn_server_rule
	uci delete firewall.vpn_server_zone
	uci delete firewall.vpn_server_wan
	uci delete firewall.vpn_server_lan
	uci commit firewall

	# clear vpn interface
	#uci delete network.vpn
	#uci commit network

	return 0
}

start_server() {
	local cfg="$1"

	command -v openvpn >/dev/null 2>&1 || return 0

	[ -z "$cfg" ] && return 0

	flush_rules && set_firewall
	/usr/sbin/openvpn --config "$cfg" --daemon --writepid /var/run/ovpn_server.pid
}

openvpn_server() {
	local enable=`uci get vpn_service.global.enable`
	if [ "$enable" != "1" ];then
		return 0
	fi

	local cfg=`uci get vpn_service.global.ovpn`
	if [ ! -e "$cfg" ];then
		logger -st $NAME -p3 "Openvpn server config no found."	
		return 0
	fi

	start_server "$cfg"
}

start() {
	openvpn_server
}

stop() {
	kill -9 $(cat /var/run/ovpn_server.pid) >/dev/null 2>&1
	flush_rules
}

